version: '2'
services:
  web:
    build: .
    ports:
        - '5656:8080'
    command: --prefix="/jenkins-ci/"
    volumes:
        - '/var/jenkins/data:/var/jenkins_home'
    container_name: 'jenkins-ci'
    restart: always
